FROM --platform=linux/amd64 nvcr.io/nvidia/tensorflow:23.01-tf2-py3
WORKDIR /app
COPY ./requirements.txt /app/requirements.txt
RUN git clone https://github.com/lmitechnologies/LMI_AI_Solutions.git
RUN pip install --upgrade pip
RUN pip3 install -r requirements.txt
# 20.09 Notes:
# -padim.dataloader requires removing AUTOTUNE input args from map() and prefetch()
# -padim.dataloader prefetch requires buffer_size argument, success with buffer_size=batch_size*4
