dataset:
  name: model
  format: folder
  path: /app/data/
  normal_dir: train/good
  normal_test_dir: null
  task: segmentation
  abnormal_dir: null  # leave null if no ground_truth
  mask: null    # leave null if no ground_truth
  extensions: null
  split_ratio: 0.2
  train_batch_size: 16
  test_batch_size: 16
  num_workers: 16
  image_size: 
  - 224
  - 224
  center_crop: null
  normalization: imagenet
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir
  test_split_ratio: 0.1
  val_split_mode: same_as_test
  val_split_ratio: 0.1
  eval_batch_size: 1

model:
  name: padim
  # backbone: wide_resnet50_2
  backbone: resnet18
  pre_trained: true
  layers:
  - layer1
  - layer2
  - layer3
  normalization_method: min_max
  n_features: 200

metrics:
  image:
  pixel:
  threshold:
    method: adaptive
    manual_image: null
    manual_pixel: null
visualization:
  show_images: false
  save_images: false
  log_images: true
  image_save_path: /app/out
  mode: full
project:
  seed: 42
  path: /app/out/results
  unique_dir: false
logging:
  logger: []
  log_graph: false
optimization:
  export_mode: torch
trainer:
  enable_checkpointing: true
  default_root_dir: /app/out/results/padim/model/run
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 50
  accelerator: auto
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle