FROM python:3.12-slim

# Install dependencies
RUN apt-get update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y --no-install-recommends libgl1
# weights_only issue will raise in pytorch>=2.6 when loading anomalib models
RUN pip install --no-cache-dir torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cpu

WORKDIR /home/gadget

# Install detectron2
RUN git clone https://github.com/facebookresearch/detectron2 detectron2
RUN pip install -e detectron2
RUN pip install scikit-learn
RUN pip install tensorboard
RUN pip install numba
RUN pip install cuda-python==12.9.0

# Install fixed version of numpy for ultralytics and albumentations
RUN pip install numpy==1.26.0 ultralytics albumentations

# Installing from anomalib src
RUN git clone -b v1.1.1 https://github.com/openvinotoolkit/anomalib.git && cd anomalib && pip install -e .
RUN anomalib install --option core
RUN pip install onnx

# copy LMI AI Solutions repository
COPY . LMI_AI_Solutions
RUN cd LMI_AI_Solutions && pip3 install -e object_detectors && pip3 install -e anomaly_detectors && pip3 install -e lmi_utils && pip3 install -e classifiers
