FROM nvcr.io/nvidia/tensorrt:25.04-py3
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install libgl1 -y
# weights_only issue will raise in pytorch>=2.6 when loading anomalib models
RUN pip install torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu124

WORKDIR /home/gadget

# Install detectron2
RUN git clone https://github.com/facebookresearch/detectron2 detectron2
RUN pip install --no-build-isolation -e detectron2
RUN pip install scikit-learn tensorboard numba cuda-python==12.9.0

# Install fixed version of numpy
RUN pip install 'numpy<2' ultralytics==8.4.24 onnx 'rfdetr<1.6.0'

# Installing anomalib
RUN pip install anomalib==2.2.0

# install git lfs 
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs

# report generation
RUN pip install pytest-html 