FROM nvcr.io/nvidia/tensorrt:25.04-py3
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install libgl1 -y
# weights_only issue will raise in pytorch>=2.6 when loading anomalib models
RUN pip install torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu124

WORKDIR /home/gadget

# Install detectron2
RUN git clone https://github.com/facebookresearch/detectron2 detectron2
RUN pip install --no-build-isolation -e detectron2
RUN pip install scikit-learn tensorboard numba cuda-python==12.9.0

# Install fixed version of numpy for ultralytics and albumentations
RUN pip install 'numpy<2' ultralytics albumentations onnx rfdetr

# Installing from anomalib src
RUN pip install anomalib==1.1.1 && anomalib install --option core

# clone LMI AI Solutions repository
RUN git clone -b ais https://github.com/lmitechnologies/LMI_AI_Solutions.git
RUN cd LMI_AI_Solutions && git submodule update --init object_detectors/submodules/yolov5
RUN cd LMI_AI_Solutions && pip3 install -e object_detectors && pip3 install -e anomaly_detectors && \
    pip3 install -e lmi_utils && pip3 install -e classifiers

# install git lfs 
RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
RUN apt-get install git-lfs

# report generation
RUN pip install pytest-html 