# FROM nvcr.io/nvidia/pytorch:22.11-py3
FROM nvcr.io/nvidia/pytorch:21.10-py3

WORKDIR /app

RUN pip3 install --upgrade pip

# RUN pip3 install torch>=1.10.1+cu113 torchvision>=0.11.2+cu113 torchaudio>=0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
RUN pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118

# partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
RUN pip install opencv-python-headless==4.3.0.38

RUN git clone https://github.com/hukaixuan19970627/yolov5_obb.git
RUN cd yolov5_obb \
    && pip install -r requirements.txt \
    && cd utils/nms_rotated \
    && python setup.py develop

RUN python -m pip install swig

RUN cd yolov5_obb/DOTA_devkit && \
    swig -c++ -python polyiou.i && \
    python setup.py build_ext --inplace

# anchor to 7.2.0 solves - The _imagingft C module is not installed
RUN pip install pillow==7.2.0
RUN pip install shapely

# COPY ./freetype_py-2.3.0-pp38-pypy38_pp73-win_amd64.whl ./
# RUN pip install freetype_py-2.3.0-pp38-pypy38_pp73-win_amd64.whl
