[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "anomaly_detectors"
version = "2.3.0.0"
description = "LMI AI Solutions anomaly detectors"

[tool.setuptools]
packages = ["anomalib_lmi", "ad_core"]

[project.scripts]
ad-convert-to-torchscript="anomalib_lmi.convert_to_torchscript:main"