FROM nvcr.io/nvidia/pytorch:23.11-py3
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /home
RUN python -m pip install --upgrade pip
RUN pip install --user 'git+https://github.com/facebookresearch/fvcore'
RUN git clone https://github.com/facebookresearch/detectron2 detectron2


RUN pip install --user -e detectron2
# RUN pip install 'git+https://github.com/facebookresearch/detectron2.git@5aeb252b194b93dc2879b4ac34bc51a31b5aee13'