FROM nvcr.io/nvidia/pytorch:22.12-py3

RUN apt-get update
RUN apt-get install python3 python3-pip -y
RUN apt-get install git libgl1 -y
WORKDIR /app

RUN pip install opencv-python==4.5.5.64 opencv-python-headless==4.5.5.64

RUN pip install anomalib

RUN git clone https://github.com/openvinotoolkit/anomalib.git

RUN pip install openvino-dev==2023.0.0 openvino-telemetry==2022.3.0 nncf==2.4.0
RUN pip install pycuda

RUN pip install nvidia-pyindex onnx-graphsurgeon

