FROM nvcr.io/nvidia/pytorch:22.07-py3

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt-get update
RUN pip install --upgrade pip

# https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo
RUN apt-get install ffmpeg libsm6 libxext6 -y
RUN pip install opencv-python==4.5.5.64
RUN pip install onnx>=1.12.0

RUN git clone https://github.com/lmitechnologies/LMI_AI_Solutions.git && cd LMI_AI_Solutions && git submodule update --init object_detectors/yolov5
RUN pip install -r LMI_AI_Solutions/object_detectors/yolov5/requirements.txt

