FROM nvcr.io/nvidia/l4t-ml:r35.1.0-py3

ARG DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8

WORKDIR /app
RUN pip3 install --upgrade pip
RUN apt-get update
RUN sudo apt-get install git -y

RUN git clone https://github.com/lmitechnologies/LMI_AI_Solutions.git && cd LMI_AI_Solutions && git submodule update --init object_detectors/yolov5
RUN pip3 install -r /app/LMI_AI_Solutions/object_detectors/yolov5/trt/arm/requirements.txt
RUN pip3 install --ignore-installed PyYAML>=5.3.1

    