data:
  class_path: anomalib.data.Folder
  init_args:
    name: dataset
    root: /app/data/
    normal_dir: train
    abnormal_dir: null
    normal_test_dir: null
    mask_dir: null
    normal_split_ratio: 0
    extensions: [".jpg"]
    image_size: [256,256]
    train_batch_size: 1
    eval_batch_size: 32
    num_workers: 8
    task: segmentation
    transform: null
    train_transform: null
    eval_transform: null
    test_split_mode: synthetic
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    seed: null

model:
  class_path: anomalib.models.EfficientAd
  init_args:
    teacher_out_channels: 384
    model_size: S
    lr: 0.0001
    weight_decay: 1.0e-05
    padding: false
    pad_maps: true

metrics:
  pixel:
    - AUROC

trainer:
  max_epochs: 1000
  max_steps: 70000

default_root_dir: /app/out
ckpt_path: null