data:
  class_path: anomalib.data.Folder
  init_args:
    name: dataset
    root: /app/data/
    normal_dir: train
    abnormal_dir: null
    normal_test_dir: null
    mask_dir: null
    normal_split_ratio: 0
    extensions: [".jpg"]
    train_batch_size: 32
    eval_batch_size: 32
    num_workers: 8
    task: segmentation
    transform:
      class_path: torchvision.transforms.v2.Compose
      init_args:
        transforms:
          - class_path: torchvision.transforms.v2.Resize
            init_args:
              size: [224, 224]
          - class_path: torchvision.transforms.v2.Normalize
            init_args:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
    train_transform: null
    eval_transform: null
    test_split_mode: synthetic
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    seed: null

model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    layers:
      - layer2
      - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9

metrics:
  pixel: AUROC

default_root_dir: /app/out
ckpt_path: null