name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ "ais" ]
  pull_request:
    branches: [ "ais" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-test-and-push:
    strategy:
      matrix:
          os: [ubuntu-latest]
          python: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          # lfs: 'true'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Install anomalib
        run: |
          anomalib install --option core

      - name: Install LMI AI Solutions packages
        run: |
          pip install -e object_detectors
          pip install -e anomaly_detectors
          pip install -e lmi_utils
          pip install -e classifiers
          
      - name: Run tests
        run: |
          echo "Running test lmi_utils..."
          pytest tests/lmi_utils

          echo "Running test object_detectors..."
          pytest tests/object_detectors

          echo "Running test classifiers..."
          pytest tests/classifiers

          echo "Running test anomaly_detectors (excluding anomalib v0 test)..."
          pytest \
            --ignore=tests/anomaly_detectors/anomalib_lmi/test_anomaly_model.py \
            tests/anomaly_detectors
