name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ "ais" ]
  pull_request:
    branches: [ "ais" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-test-and-push:
    strategy:
      matrix:
          os: [ubuntu-latest]
          python: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      # 1. Check out the repository's code
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          # lfs: 'true'

      # 2. Install dependencies for building docker image
      - name: Install dependencies
        run: |
          pip install --no-cache-dir torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cpu
          git clone https://github.com/facebookresearch/detectron2 detectron2
          pip install -e detectron2
          pip install scikit-learn
          pip install tensorboard
          pip install numba
          pip install cuda-python
          pip install numpy==1.26.0 ultralytics albumentations
          git clone -b v1.1.1 https://github.com/openvinotoolkit/anomalib.git && cd anomalib && pip install -e .
          anomalib install --option core
          pip install onnx

      # 3. Install packages
      - name: Install LMI AI Solutions packages
        run: |
          pip install -e object_detectors
          pip install -e anomaly_detectors
          pip install -e lmi_utils
          pip install -e classifiers

      # 4. Run tests
      - name: Run tests
        run: |
          echo "Running test lmi_utils..."
          pytest tests/lmi_utils

          echo "Running test object_detectors..."
          pytest tests/object_detectors

          echo "Running test classifiers..."
          pytest tests/classifiers

          echo "Running test anomaly_detectors (excluding anomalib v0 test)..."
          pytest \
            --ignore=tests/anomaly_detectors/anomalib_lmi/test_anomaly_model.py \
            tests/anomaly_detectors
