name: Build and Publish Test Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-push-test-env:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        python-version: ['3.12']

    env:
      IMAGE_NAME: ghcr.io/lmi-ai-solutions/test-env

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
               
      - name: Install anomalib and detectron2
        run: |
          git clone https://github.com/facebookresearch/detectron2 detectron2
          pip install --no-build-isolation -e detectron2
          git clone -b v1.1.1 https://github.com/openvinotoolkit/anomalib.git && cd anomalib && pip install -e .
          anomalib install --option core

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}   # This is your GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=py${{ matrix.python-version }}
            type=raw,value=latest,enable=${{ matrix.python-version == '3.12' }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .       # Use the root of the repo for the build context
          push: true       # Push the image after building
          tags: |          # List of tags
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}