name: CI

on:
  push:
    branches: [ "ais" ]
  pull_request:
    branches: [ "ais" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      docs_only: ${{ steps.filter.outputs.docs_only }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          submodules: false
          fetch-depth: 0
          
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs_only:
              - '**/*.yaml'
              - 'docs/**'
              - '**/*.md'
              - '.gitignore'
              - '.gitattributes'

  run-test:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.docs_only != 'true' && github.head_ref != 'update-pre-commit-hooks' }}
    
    strategy:
      matrix:
        runner-config:
          - runner: ubuntu-latest
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64
        python-version: ['3.10']
        test_suite: ["no-AD", "AD"]
    
    timeout-minutes: 30
    runs-on: ${{ matrix.runner-config.runner }}
    
    container:
      image: ghcr.io/lmitechnologies/ais-test-env:py${{ matrix.python-version }}-${{ matrix.runner-config.arch }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: 'true'

      - name: Mark workspace as safe
        run: git config --global --add safe.directory $(pwd)

      - name: Create Git LFS file list
        run: git lfs ls-files -l |cut -d' ' -f1 |sort >.git/lfs-hashes.txt

      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            lfsdata-v1-
            lfsdata

      - name: Fetch any needed Git LFS objects and prune extraneous ones
        run: git lfs fetch --prune

      - name: Check out Git LFS content
        run: git lfs checkout

      - name: Install LMI AI Solutions packages
        run: |
          pip install -e object_detectors -e anomaly_detectors -e lmi_utils -e classifiers
          
      - name: Run tests
        shell: bash
        run: |
          OTHER_TEST_SUITE=(lmi_utils object_detectors classifiers)
          
          if [ "${{ matrix.test_suite }}" == "AD" ]; then
            pytest --ignore=tests/anomaly_detectors/anomalib_lmi/test_anomaly_model.py tests/anomaly_detectors
          else
            for suite in "${OTHER_TEST_SUITE[@]}"; do
              pytest tests/${suite}
            done
          fi
