name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write      # To create tags and releases
      issues: write      # To comment on issues
      pull-requests: write # To comment on PRs

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/github @semantic-release/changelog @semantic-release/git @semantic-release/exec

      - name: Manual Script Test
        run: python3 .github/workflows/scripts/update_versions.py 1.6.0-test

      - name: Run semantic-release
        run: npx semantic-release --dry-run
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}