name: Test

on:
  push:
    branches: [ "ais" ]
  pull_request:
    branches: [ "ais" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build-and-test:
    strategy:
      matrix:
          os: [ubuntu-latest]
          python: ["3.12"]
          test_suite: ["lmi_utils", "object_detectors", "classifiers", "anomaly_detectors"]
    runs-on: ${{ matrix.os }}
    name: Test ${{ matrix.test_suite }} with Python ${{ matrix.python }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Create Git LFS file list
        run: git lfs ls-files -l |cut -d' ' -f1 |sort >.git/lfs-hashes.txt

      - name: Restore Git LFS object cache
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfsdata-v1-${{ hashFiles('.git/lfs-hashes.txt') }}
          restore-keys: |
            ${{ runner.os }}-lfsdata-v1-
            ${{ runner.os }}-lfsdata

      - name: Fetch any needed Git LFS objects and prune extraneous ones
        run: git lfs fetch --prune

      - name: Check out Git LFS content
        run: git lfs checkout

      # - name: Set up Python with pip caching
      #   uses: actions/setup-python@v6
      #   with:
      #     python-version: ${{ matrix.python }}
      #     cache: 'pip'
      #     cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
               
      - name: Install anomalib and detectron2
        run: |
          git clone https://github.com/facebookresearch/detectron2 detectron2
          pip install --no-build-isolation -e detectron2
          git clone -b v1.1.1 https://github.com/openvinotoolkit/anomalib.git && cd anomalib && pip install -e .
          anomalib install --option core

      - name: Install LMI AI Solutions packages
        run: |
          pip install -e object_detectors
          pip install -e anomaly_detectors
          pip install -e lmi_utils
          pip install -e classifiers
          
      - name: Run tests
        run: |
          if [ "${{ matrix.test_suite }}" == "lmi_utils" ]; then
            pytest tests/lmi_utils
          elif [ "${{ matrix.test_suite }}" == "object_detectors" ]; then
            pytest tests/object_detectors
          elif [ "${{ matrix.test_suite }}" == "classifiers" ]; then
            pytest tests/classifiers
          elif [ "${{ matrix.test_suite }}" == "anomaly_detectors" ]; then
            pytest \
              --ignore=tests/anomaly_detectors/anomalib_lmi/test_anomaly_model.py \
              tests/anomaly_detectors
