name: Update Pre-commit Hooks

on:
  schedule:
    # This runs every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch: # Allows you to trigger it manually for testing

jobs:
  update-hooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update hooks
        run: |
          pip install pre-commit
          pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update pre-commit hooks"
          title: "Update Pre-commit Hooks"
          body: "This is an automated PR to update the pre-commit hooks to their latest versions."
          branch: update-pre-commit-hooks
          delete-branch: true