name: Update Pre-commit Hooks

on:
  schedule:
    # This runs every Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch: # Allows you to trigger it manually for testing

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  update-hooks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ secrets.AIS_CI_APP_ID }}
          private-key: ${{ secrets.AIS_CI_APP_KEY }}

      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Update hooks
        run: |
          pip install pre-commit
          pre-commit autoupdate

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "chore: update pre-commit hooks"
          title: "Update Pre-commit Hooks"
          body: "This is an automated PR to update the pre-commit hooks to their latest versions."
          branch: update-pre-commit-hooks
          labels: "dependencies, precommit"
          delete-branch: true